global:
  scrape_interval: 1s # Bad!! just for demo

scrape_configs:
  - job_name: 'opentelemetry'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
    # - targets: ['todo:9464','auth:9464']
    - targets: ['collector:8889']
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['collector:8888']
          